apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  namespace: {APPNAME}
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
        - image: registry.gitlab.com/goatlab/image/nginx:1.7
          name: nginx
          ports:
            - containerPort: 80
              name: nginx-http
            - containerPort: 443
              name: nginx-https
          env:
            - name: NGINX_SERVER_NAME
              valueFrom:
                configMapKeyRef:
                  name: wp-config
                  key: NGINX_SERVER_NAME
            - name: NGINX_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: wp-config
                  key: NGINX_CONFIG
            - name: NGINX_DEV_INSTALL
              valueFrom:
                configMapKeyRef:
                  name: wp-config
                  key: NGINX_DEV_INSTALL
            - name: PHP_FPM_UPSTREAM
              valueFrom:
                configMapKeyRef:
                  name: wp-config
                  key: PHP_FPM_UPSTREAM
            - name: NGINX_DOCROOT
              valueFrom:
                configMapKeyRef:
                  name: wp-config
                  key: NGINX_DOCROOT
            - name: NGINX_PROXY_UPSTREAM
              valueFrom:
                configMapKeyRef:
                  name: wp-config
                  key: NGINX_PROXY_UPSTREAM
            - name: REDIS_UPSTREAM
              valueFrom:
                configMapKeyRef:
                  name: wp-config
                  key: REDIS_UPSTREAM
            - name: WORDPRESS_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: wp-config
                  key: WORDPRESS_DB_HOST
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: wp-config
                  key: WORDPRESS_DB_PASSWORD
            - name: WORDPRESS_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: wp-config
                  key: WORDPRESS_DB_USER
            - name: WORDPRESS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: wp-config
                  key: WORDPRESS_DB_NAME
      imagePullSecrets:
        - name: regcred
