apiVersion: v1
kind: Service
metadata:
  namespace: {APP_NAME}
  name: nginx
  labels:
    app: {APP_NAME}
spec:
  #loadBalancerIP: 40.70.189.96
  ports:
    - port: 80
      name: nginx-http
    - port: 443
      name: nginx-https
  selector:
    app: nginx
  type: LoadBalancer
