apiVersion: v1
kind: Service
metadata:
  namespace: {APP_NAME}
  name: redis
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      name: redis-default
  selector:
    app: redis
  type: ClusterIP
