apiVersion: v1
kind: Service
metadata:
  namespace: {APP_NAME}
  name: wordpress
  labels:
    app: {APP_NAME}
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: wordpress
  type: ClusterIP
